run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - deadcode

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck